config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :users
  root 'items#index'
  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index' 
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :comments, only: :create
  end
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  resources :users, only: [:show, :create, :new] do
    collection do
      get 'logout'
      get 'card'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :points, dependent: :destroy
  has_one  :deliver_adresses, dependent: :destroy
  has_many :cards
  has_many :comments

  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day, :password, :email, :delivery_first_name, :delivery_family_name, :delivery_first_name_kana, :delivery_family_name_kana, :prefectures, :municipality, :address, :postal_code, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      else
      render ‘create’
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @items = Item.where(saler_id: @user.id)
    @item_images = ItemImage.where(item_id: @items.ids)
    @parents =Category.where(ancestry: nil).limit(13)
  end 

  def logout
    @parents =Category.where(ancestry: nil).limit(13)
  end

  def card
    @parents =Category.where(ancestry: nil).limit(13)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_itemlist.html.haml
%br.productLists
  - @items.each do|item|
    .productList
      - item.item_images.first(1).each do |image|
        = link_to image_tag(image.image_url.url,class: "productList__img"),item_path(item)
      - if item.trading_status == 0
        .soldout
          .soldout__text SOLD OUT   
      .productList__body
        %h3.name
        = item.name
        .details
          %ul 
            %li 
              = item.price
            %h5 円
            %li
              %i.fa.fa-star.likeIcon (税込)
            %h6 👍9670

app/views/users/_topfooter.html.haml
.top-banner
  .top-banner__in
    %h2.top-banner__in__title だれでもかんたん、人生を変えるフリマアプリ
    %p.top-banner__in__text 今すぐ無料ダウンロード！
    .top-banner__in__icon
      = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "apple3")
      = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class: "google3")

.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社)"
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "FURIMA利用規約"
        %li
          = link_to "ポイントに関する特約"
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド"
        %li
          = link_to "FURIMAロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
  .footer__logo
    = link_to image_tag("logo-white.png",class: "orz2")
  %p © FURIMA

.exhibision-btn
  .exhibision-btn__item
    出品する
    = link_to image_tag("icon_camera.png", size: "54x54", class: "footer__icon"),new_item_path(@new)

app/views/users/_tophead.html.haml
.topHeader
  .headerInner
    .mainheader
      %h1.icon
        = link_to image_tag("logo.png"),root_path
        
      .search-box
        %form{"accept-charset": "UTF-8", action: "#", method: "get"}
          %input{name:  "utf8", type: "hidden", value: "✓"}/
          %input#searchInput.searchBox--input{name: "key", placeholder: "キーワードから探す"}/
          %button{type: "submit"}
            .search-item
              = image_tag 'icon-search 1.png'
            %input{name: "authenticity_token", type: "hidden", value: "+Z5TWFAnhn4nyERwyq8tGeL24RWLf6d/DXQga++bhRyXAu8YJ5uoGBiBOvHimDNE1x9srYXVjnFOgiOPbUdCzQ=="}/
    %ul.top-nav
      .listleft
        %ul.listleft-item1
          %li.posi
            = link_to "カテゴリー"
            %ul.listitem
              %li
                -# - @parents.each do |parent|
                -#   = link_to "#{parent.name}",id: "#{parent.id}"
        .listleft-item2
        = link_to "ブランド"
      .listright
        - if user_signed_in?
          = link_to "マイページ", user_path(current_user)
        - else
          = link_to "ログイン",new_user_session_path(@new_user_session), class: "listright-item1"
          = link_to "新規会員登録",new_user_registration_path, class: "listright-item2"

app/views/users/card.html.haml
.background 
  .mypage
    = render '/users/tophead'
    .mypage-side
      %ul.mypage-side__box
        %li
          = link_to user_path(current_user) do
            %span マイページ
            %span >
        %li
          = link_to "/items/new" do
            %span 出品する
            %span >
        %li
          = link_to "#" do
            %span ガイド
            %span >
        %li
          = link_to "#" do
            %span お問い合わせ
            %span >
      %h3.mypage-side__section-title
        設定
      %ul.mypage-side__box
        %li
          = link_to "/users/card" do
            %span 支払い方法
            %span >
        %li
          = link_to "/users/logout" do
            %span ログアウト
            %span >
    .card
      .card__top
        %h2 支払い方法
      .card__center
        %h3 クレジットカード一覧
        = link_to "/card/new" do
          .add-card-btn
            %span クレジットカードを追加する
      .card__bottom
        = link_to "#" do
          %span 支払い方法について
          %span ＞
  .muypage__footer
    = render 'users/topfooter'
          

app/views/users/logout.html.haml
.background 
  .mypage
    = render 'tophead'
    .mypage-side
      %ul.mypage-side__box
        %li
          = link_to user_path(current_user) do
            %span マイページ
            %span >
        %li
          = link_to "/items/new" do
            %span 出品する
            %span >
        %li
          = link_to "#" do
            %span ガイド
            %span >
        %li
          = link_to "#" do
            %span お問い合わせ
            %span >
      %h3.mypage-side__section-title
        設定
      %ul.mypage-side__box
        %li
          = link_to "/users/card" do
            %span 支払い方法
            %span >
        %li
          = link_to "/users/logout" do
            %span ログアウト
            %span >
    .logout
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout__btn'
  .mypage__footer
    = render 'topfooter'
    

app/views/users/show.html.haml
.background 
  .mypage
    = render "tophead"
    .mypage-side
      %ul.mypage-side__box
        %li
          = link_to user_path(current_user) do
            %span マイページ
            %span >
        %li 
          = link_to "/items/new" do
            %span 出品する
            %span >
        %li
          = link_to "#" do
            %span ガイド
            %span >
        %li
          = link_to "#" do
            %span お問い合わせ
            %span >
      %h3.mypage-side__section-title
        設定
      %ul.mypage-side__box
        %li
          = link_to "/users/card" do
            %span 支払い方法
            %span >
        %li
          = link_to "#" do
            %span 発送元・お届け先住所
            %span >
        %li
          = link_to "/users/logout" do
            %span ログアウト
            %span >
    .mypage-main
      .mypage-main__top
        .icon
          = image_tag 'https://picsum.photos/180/180'
        .name
          =@user.nickname
        .score
          %span 評価68
          %span 出品数100
      .mypage-main__status
        .good
          %span 😄
          %span 60
        .normal
          %span 😏
          %span 8
        .bad        
          %span 😩
          %span 0  
      .mypage-main__sns
        = link_to image_tag('facebook.png'),"#"
        = link_to image_tag('twitter.jpg'),"#"
        = link_to image_tag('LINE_APP.png'),"#"
      .mypage-main__index
        %p.index-title この出品者の商品
        = render 'itemlist'
  .mypage__footer 
    =render "topfooter"  