config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :users
  root 'items#index'
  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index' 
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :comments, only: :create
  end
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  resources :users, only: [:show, :create, :new] do
    collection do
      get 'logout'
      get 'card'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category_user, optinal:true

  # validates :name,presence: true
end

app/models/category_user.rb
class CategoryUser < ActiveHash::Base
  self.data = [
    {id: 1, name: 'レディース'}, {id: 2, name: 'ベビー・キッズ'}, {id: 3, name: 'インテリア・住まい・小物'},
                  {id: 4, name: '本・音楽・ゲーム'}, {id: 5, name: 'おもちゃ・ホビー・グッズ'}, {id: 6, name: 'コスメ・香水・美容'},
                  {id: 7, name: '家電・スマホ・カメラ'}, {id: 8, name: 'スポーツ・レジャー'}, {id: 9, name: 'チケット'}
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :text, presence: true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id:3, name: '目立った傷や汚れなし'}, {id:4, name: '全体的に状態が悪い'}
  ]
end

app/models/deliver_adress.rb
class DeliverAdress < ApplicationRecord
  belongs_to :user
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
                {id: 1, name: '送料込み（配送者負担）'}, {id: 2, name: '着払い（購入者負担）'}
              ]
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :shipping
  belongs_to :saler, class_name: "User",optional:true
  belongs_to :buyer, class_name: "User",optional:true
  belongs_to :user,optional:true
  belongs_to :category,optional:true
  belongs_to :brand,optional:true
  has_many :item_images, dependent: :destroy
  belongs_to :size,optional:true
  has_many :comments
  accepts_nested_attributes_for :item_images, allow_destroy: true
  accepts_nested_attributes_for :shipping, update_only: true
  accepts_nested_attributes_for :category
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition

  validates :name, :text, :price, :trading_status, :condition_id, presence: true
  validates :item_images, presence: true
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  mount_uploader :image_url, ImageUploader
  belongs_to :item 

  validates :image_url, presence: true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :item 
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :delivery_handlingtime
  include JpPrefecture
  jp_prefecture :prefecture_code

  validates :prefecture_code, :delivery_handlingtime_id ,:delivery_fee_id, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :points, dependent: :destroy
  has_one  :deliver_adresses, dependent: :destroy
  has_many :cards
  has_many :comments

  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day, :password, :email, :delivery_first_name, :delivery_family_name, :delivery_first_name_kana, :delivery_family_name_kana, :prefectures, :municipality, :address, :postal_code, presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成
    Payjp.api_key =  Rails.application.credentials[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      email: current_user.email, 
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースの削除
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key =  Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    @parents =Category.where(ancestry: nil).limit(13)
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key =  Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_login, except: [:index, :show]

  def index
    @items =Item.order("id desc").limit(4)
    @item_images = ItemImage.all
    @parents =Category.where(ancestry: nil).limit(13)

  end

  def new
    @item = Item.new
    @item.item_images.new
    @item.build_shipping
    @item.build_category
    @categories = Category.where(ancestry: nil).limit(13)
  end
  
  def create
    @item = Item.create(item_update_params)
    @categories = Category.where(ancestry: nil).limit(13)
    if @item.save
      #  @item_images.save
      redirect_to root_path
    else
      render :new
    end

  end

  def show
    @item = Item.find(params[:id])
    @item_images = @item.item_images.limit(8)
    @parent = @item.category
    @shipping = @item.shipping 
    @comment = Comment.new
    @comments = @item.comments.includes(:user) 
  end

  def edit
    @item = Item.find(params[:id])
    @item_images = @item.item_images.limit(5)
    @parent = @item.category
    @categories = Category.where(ancestry: nil).limit(13)
    unless current_user.id == @item.saler.id
      redirect_to root_path
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.saler_id == current_user.id && user_signed_in?
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path(@item)
      flash[:alert] ='削除に失敗しました'
    end
end

  def update
    @item = Item.find(params[:id])
    @item.update(item_update_params)
    redirect_to item_path(@item)
  end


  private
  def items_params
    params.require(:item).permit(:name, :condition_id, :text, :price, :trading_status, :buyer, :saler, :completed_at, shipping_attributes: [:delivery_fee_id, :delivery_handlingtime_id, :prefecture_code], category_attributes: [:name], item_images_attributes: %i[image_url]).merge(saler_id: current_user.id)
  end

  def item_update_params
    params.require(:item).permit(:name, :condition_id, :text, :price, :trading_status, :buyer, :saler, :completed_at, shipping_attributes: [:delivery_fee_id, :delivery_handlingtime_id, :prefecture_code], item_images_attributes:[:image_url,:_destroy,:id], category_attributes: [:name]).merge(saler_id: current_user.id)
  end

  def move_to_login
    redirect_to user_session_path unless user_signed_in?
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/card/new.html.haml
.background 
  .mypage
    = render 'users/tophead'
    .mypage-side
      %ul.mypage-side__box
        %li
          = link_to user_path(current_user) do
            %span マイページ
            %span >
        %li
          = link_to "/items/new" do
            %span 出品する
            %span >
        %li
          = link_to "#" do
            %span ガイド
            %span >
        %li
          = link_to "#" do
            %span お問い合わせ
            %span >
      %h3.mypage-side__section-title
        設定
      %ul.mypage-side__box
        %li
          = link_to "/users/card" do
            %span 支払い方法
            %span >
        %li
          = link_to "/users/logout" do
            %span ログアウト
            %span >
    .card
      .card__top
        %h2 クレジットカード情報入力
      .card__form
        = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %label.card-form-agenda カード番号
          %span.form-require 必須
          %br/
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %br
          %ul.card-list 
            %li.card-list--item{ style: "margin-left: 0;"}
              = image_tag "visa.svg", width:"49", height:"20"
            %li.card-list--item
              = image_tag "master-card.svg", width:"34", height:"20"
            %li.card-list--item  
              = image_tag "saison-card.svg", width:"30", height:"20"
            %li.card-list--item  
              = image_tag "jcb.svg", width:"32", height:"20"
            %li.card-list--item
              = image_tag "american_express.svg", width:"21", height:"20"
            %li.card-list--item
              = image_tag "dinersclub.svg", width:"32", height:"20"
            %li.card-list--item 
              = image_tag "discover.svg", width:"32", height:"20"
          %label.card-form-agenda 有効期限
          %span.form-require 必須
          %br/
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          %span 月 
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
          %br
          %label.card-form-agenda セキュリティコード
          %span.form-require 必須
          %br/
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁または3桁の番号", maxlength: "4", id: "cvc"
          #card_token
          = submit_tag "追加する", id: "token_submit"
  .mypage__footer
    = render 'users/topfooter'
    

app/views/card/show.html.haml
.background 
  .mypage
    = render 'users/tophead'
    .mypage-side
      %ul.mypage-side__box
        %li
          = link_to user_path(current_user) do
            %span マイページ
            %span >
        %li
          = link_to "/items/new" do
            %span 出品する
            %span >
        %li
          = link_to "#" do
            %span ガイド
            %span >
        %li
          = link_to "#" do
            %span お問い合わせ
            %span >
      %h3.mypage-side__section-title
        設定
      %ul.mypage-side__box
        %li
          = link_to "/users/card" do
            %span 支払い方法
            %span >
        %li
          = link_to "/users/logout" do
            %span ログアウト
            %span >
    .card
      .card__top
        %h2 登録クレジットカード情報
      .card__form
        %p カード番号
        = "**** **** **** " + @default_card_information.last4 
        %p 有効期限
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button カードを削除する
        = link_to root_path do
          %span.top-link トップページへ 
  .mypage__footer
    = render 'users/topfooter'
    

app/views/items/_error_messages.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/items/_newfooter.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社)"
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "FURIMA利用規約"
        %li
          = link_to "ポイントに関する特約"
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド"
        %li
          = link_to "FURIMAロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
  .footer__logo
    = link_to image_tag("logo-white.png",class: "orz2")
  %p © FURIMA

app/views/items/index.html copy.haml
.topHeader
  .headerInner
    .mainheader
      %h1.icon
        = link_to image_tag("logo.png"),root_path
      .search-box
        %form{"accept-charset": "UTF-8", action: "#", method: "get"}
          %input{name:  "utf8", type: "hidden", value: "✓"}/
          %input#searchInput.searchBox--input{name: "key", placeholder: "キーワードから探す"}/
          %button{type: "submit"}
            .search-item
              = image_tag 'icon-search 1.png'
            %input{name: "authenticity_token", type: "hidden", value: "+Z5TWFAnhn4nyERwyq8tGeL24RWLf6d/DXQga++bhRyXAu8YJ5uoGBiBOvHimDNE1x9srYXVjnFOgiOPbUdCzQ=="}/

    %ul.top-nav
      .listleft
        %ul.listleft-item1
          %li.posi
            = link_to "カテゴリー"
            %ul.listitem
              %li
                - @parents.each do |parent|
                  = link_to "#{parent.name}",id: "#{parent.id}"
        .listleft-item2
        = link_to "ブランド"
      .listright
        - if user_signed_in?
          = link_to "マイページ", user_path(current_user)
        - else
          = link_to "ログイン",new_user_session_path(@new_user_session), class: "listright-item1"
          = link_to "新規会員登録",new_user_registration_path, class: "listright-item2"

.top-main
  .top-main__visual
    .top-main__visual__content
      %h2.top-main__visual__content__title
        %br/
        人生を変えるフリマアプリ
      %p.top-main__visual__content__word
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .top-main__visual__content__button
        = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "apple")
        = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class: "google")

  .top-main__merit
    .top-main__merit__title 
      %h2
        FURIMAが選ばれる3つの理由
    %ul.top-main__merit__kind
 
      %li.top-main__merit__kind__one
        .top-main__merit__kind__one__pic
          %span.top-main__merit__kind__one__pic__number1
            %p 1
          = image_tag "pict-reason-01.jpg",class: "phone"
        %h3.top-main__merit__kind__one__text
          %span.top-main__merit__kind__one__text__left 3分
          ですぐに出品
        %p.top-main__merit__kind__one__text2
          スマホで入力するだけで簡単に出品できる！

      %li.top-main__merit__kind__one
        .top-main__merit__kind__one__pic
          %span.top-main__merit__kind__one__pic__number1
            %p 2
          = image_tag "pict-reason-02.jpg",class: "phone"
        %h3.top-main__merit__kind__one__text
          %span.top-main__merit__kind__one__text__left シンプル
          で使いやすい
        %p.top-main__merit__kind__one__text2
          めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.top-main__merit__kind__one
        .top-main__merit__kind__one__pic
          %span.top-main__merit__kind__one__pic__number1
            %p 3
          = image_tag "pict-reason-03.jpg",class: "phone"
        %h3.top-main__merit__kind__one__text
          手数料
          %span.top-main__merit__kind__one__text__left 業界最安
        %p.top-main__merit__kind__one__text2
          最大3%でお得に出品&amp;購入！


  .top-main__visual2
    .top-main__visual2__content
      %h2.top-main__visual2__content__title 会員数日本一位
      %p.top-main__visual2__content__text 
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .top-main__visual2__content__button
        = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "apple2")
        = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class: "google2")

.character
.heads FURIMAの特徴
.convenients
  .convenient
    .convenient__img
      = image_tag "icon-01.png",class: "orz"
    %h3.convenient__subtitle 簡単に売り買いできる
    %p.convenient__detail
      スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
  .convenient
    .convenient__img
      = image_tag "icon-03.png",class: "orz"
    %h3.convenient__subtitle 売上金は即日振込みに対応
    %p.convenient__detail
      午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
  .convenient
    .convenient__img
      = image_tag "icon-04.png",class: "orz"
    %h3.convenient__subtitle 様々な支払いに対応
    %p.convenient__detail
      お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
.pickupcategory
  %h2.heads2 ピックアップカテゴリー
  .productbox
  .productbox__Head
    = link_to "新規投稿商品",class:"name" 
  .productLists
  - @items.each do|item|
    .productList
      - item.item_images.first(1).each do |image|
        = link_to image_tag(image.image_url.url),item_path(image)
      - if item["trading_status"] ==0
        .soldout
          .soldout__text SOLD OUT   
      .productList__body
        %h3.name
        = item.name
        .details
          %ul 
            %li 
              = item.price
            %h5 円
            %li
              %i.fa.fa-star.likeIcon (税込)
            %h6 👍9670
.top-banner
  .top-banner__in
    %h2.top-banner__in__title だれでもかんたん、人生を変えるフリマアプリ
    %p.top-banner__in__text 今すぐ無料ダウンロード！
    .top-banner__in__icon
      = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "apple3")
      = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg",class: "google3")

.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社)"
        %li
          = link_to "プライバシーポリシー"
        %li
          = link_to "FURIMA利用規約"
        %li
          = link_to "ポイントに関する特約"
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧"
        %li
          = link_to "ブランド一覧"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド"
        %li
          = link_to "FURIMAロゴ利用ガイドライン"
        %li
          = link_to "お知らせ"
  .footer__logo
    = link_to image_tag("logo-white.png",class: "orz2")
  %p © FURIMA


.exhibision-btn
  .exhibision-btn__item
    出品する
    = link_to image_tag("icon_camera.png", size: "54x54", class: "footer__icon"),new_item_path(@new)

app/views/items/show.html.haml
.shows
  = render 'newhead'
  .show
    .show__top
      = @item.name
    .show__image
      - @item.item_images.first(1).each do |image|
        = image_tag image.image_url.url
    %br.show__images
      %ul
        %li
        - @item.item_images.each do |image|
          = image_tag(image.image_url.url,  size:"140x87")
    .show__price
      %span
      ¥
      = @item.price
      円
    .show__tax
      %span（税込)
    .show__text
      = simple_format(@item.text)
    .show__details
      %table
        %tr
          %th 出品者
          %td 
            = link_to @item.saler.nickname, user_path(@item.saler)
        %tr
          %th カテゴリー
          %td
            = @item.category.name
        %tr
          %th 商品状態
          %td
            = @item.condition.name
        %tr
          %th 発送料の負担
          %td
            = @item.shipping.delivery_fee.name
        %tr
          %th 発送元の地域
          %td 
            = @item.shipping.prefecture.name
        %tr
          %th 発送日の目安
          %td
            = @item.shipping.delivery_handlingtime.name
    .show__option
      %ul
        %li
          = link_to "★ お気に入り 1", "#", class: "show__option__like"
        - if user_signed_in?
          - if @item.trading_status == 0
            %li 
              %h4.show_status SOLD OUT
          - elsif @item.trading_status == 1 && @item.saler.id == current_user.id
            %li
          - else 
            %li
              = link_to "購入画面に進む", item_purchase_index_path(@item) , class: "show__option__report"
        - else 
          - if @item.trading_status == 0
            %li 
              %h4.show_status SOLD OUT
          - else 
            %li
              = link_to " 購入画面に進む (ログインが必要です）", user_session_path, class: "show__option__report"
        - if user_signed_in? && @item.saler.id == current_user.id
          = link_to "編集",edit_item_path
          = link_to "削除" ,item_path(@item) ,data:{confirm: "本当に削除しますか？"},method: :delete 
  - if current_user
    .show__comments
      .show__comments-index
        -if @comments
          - @comments.each do |comment|
            %p.each-comment
              %span
                = link_to comment.user.nickname, user_path(comment.user)
                = ' : '  
                = comment.text
                %span.comment-time
                  = time_ago_in_words(comment.created_at) + '前'
      = form_for [@item, @comment] do |f|
        = h(flash[:notice])
        = render 'items/error_messages', model: f.object
        = f.text_area :text, class:"show__comments__text", placeholder: "コメントする"
        .show__comments__notice
          相手のことを考え丁寧なコメントをしましょう
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        .show__comments__btn 
          = f.submit "コメントする", class:"show__comments__btn__i"

  .show__bottom
    .show__bottom__next
      = link_to "<前の商品", root_path, class: "show__bottom__next__left"
      = link_to "後ろの商品>", "#", class: "show__bottom__next__right"
    .show__bottom__lists
      = link_to "メンズをもっと見る", "#", class: "show__bottom__lists__list"

  .exhibision-btn
    .exhibision-btn__item
      出品する
      = link_to image_tag("icon_camera.png", size: "54x54", class: "footer__icon")
  .exhibision-footer
    = render "showfooter"